package com.pl.aga.services;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import MPR_Project_8195.Employee;


public class EmployeeDBManager {

	private Connection conn;

	private Statement stmt;

	private PreparedStatement addEmployeeStmt;
	private PreparedStatement getEmployeeStmt;


	public EmployeeDBManager()
	{
		try {
			

			conn= DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

			stmt=conn.createStatement();
			boolean employeeTableExists=false;

			ResultSet rs= conn.getMetaData().getTables(null, null, null, null);

			while(rs.next())
			{
				if("Employee".equalsIgnoreCase(rs.getString("TABLE_NAME")))
					{
						employeeTableExists=true;
						break;
					}
			}


			if(!employeeTableExists)
			{
				stmt.executeUpdate("" +
					"CREATE TABLE employee(" +
					"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
					"name varchar(20)," +
					"" +
					")");
			}

			addEmployeeStmt=conn.prepareStatement("" +
					"INSERT INTO employee (name) VALUES (?)" +
					"");

			getEmployeeStmt=conn.prepareStatement("" +
					"SELECT * FROM employee" +
					"");



		} catch (SQLException e) {

			e.printStackTrace();
		}
	}

	public void addEmployee(Employee p)
	{
		try {
			addEmployeeStmt.setString(1, p.getName());

			addEmployeeStmt.executeUpdate();

		} catch (SQLException e) {

			e.printStackTrace();
		}

	}

	public List<Employee> getAllEmployees()
	{
		List<Employee> employee=new ArrayList<Employee>();

		try {
			ResultSet rs= getEmployeeStmt.executeQuery();

			while(rs.next())
			{
				employee.add(new Employee(rs.getString("Name"), null, 0, 0, 0));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return employee;
	}


}


